# modelUrl: "file:///C:/Users/martin/Projects/models/core-types/core-types.xml"
modelFileUrl: "https://github.com/olliehaigh/core-types/blob/master/core-types.xml"
imagesDir: "images"
# queries:
types: "Core Types"
outputDirUrl: "https://github.com/olliehaigh/core-types/tree/master/generated/"
# outputDirUrl: "file:/core-types/generated"
modelConfig:
  typesPackageName: "Types"
  defaults:
    classActions:
      - CREATE
      - READ
loader:
  configFileUrl: "https://github.com/olliehaigh/core-types/blob/master/config/loaders/ea-xmi/config.yaml"
  outputSubDir: "mtt-models"
generators:
  #  openapi:
  #  configUrl: "file:///C:/Users/martin/Projects/models/core-types/config/generators/openapi/config.yaml"
  #  graphql: "config/generators/graphql/application.yaml" # This is the path relative to the basePath
  aoco:
    configFileUrl: "https://github.com/olliehaigh/core-types/blob/master/config/generators/aoco/aoco.yaml"
    outputSubDir: "specs/aoco"
#  mkdoc: "config/generators/mkdoc/application.yaml" # This is the path relative to the basePath
